### ISSUE TITLE
Inhalte 

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#10]
http://gimmick.ayo-gawe.com/inhalte/

![2016-02-09-114156_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/12913992/2c9dd73a-cf22-11e5-839c-a8d649b021bc.png)

ini Inhalte layoutnya bener yah? setahu sy ada garis disini dia.

**Comment by shandya** [comment]
Iya harusnya ada garis, namun saya masih agak kesulitan implementasinya (karena menyangkut responsive dll). Sekarang masih dicari dulu solusinya.

**Comment by erwin-gimmick** [comment]
buat mobile hilangin aja linenya.
