### ISSUE TITLE
Testzugang Tools & Contact Form

### ISSUE THREAD

**Issue by shandya** [shandya/gimmickmedia#11]
![gimmick-tools](https://cloud.githubusercontent.com/assets/4597656/12936921/ce176eba-cfd5-11e5-8b0b-34bb596fdb1e.jpg)

Masih kurang jelas action section ini apa ya? Semacam email subscription atau gimana.

**Comment by erwin-gimmick** [comment]
Itu cuma Email aja sih, kyk kontakt gitu. kl di submit, ada email kirim k kt dengan nama, company and email aja.

**Comment by erwin-gimmick** [comment]
Shandy, tinggal ini aja berarti? Ini sebenarnya sama aja sih ama contact form, bedanya, ini bukan buat kommunikasi, melainkan info, kalo mereka tertarik ama sistem elearning kt gt. n mereka musti masukin email, nama, ama nama company. dari situ nanti di contact lgsung. jadi bukan newsletter.
