### ISSUE TITLE
Section Contact background 

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#13]
bisa tolong di update k css nya Shandy, biar gambar peta nya tampil semua

background-size: contain;
background-repeat: no-repeat;

ama yang ini juga 
_navbar.scss 335 ada text-decorationnya "underline"  tolong di hilangin
![auswahl_001](https://cloud.githubusercontent.com/assets/8277695/12955929/a58b6b22-d025-11e5-89f3-02af989b5af8.png)

.agentur-menu-item a:hover, .agentur-menu-item.current-menu-item a {
    border-right: 8px solid #192340;
}

PS: underlined nya cuma ada pas focus aja.

**Comment by shandya** [comment]
Perbaikan gambar peta dan text decorationnya sudah dipush, bisa dicek lagi.

**Comment by erwin-gimmick** [comment]
Text decorationnya kykna masih ada linenya itu. dia cuma muncul pas focus aja.

tambahin ini aja k scss nya

.navbar .nav-list-item a:focus {
    text-decoration: none;
}
