### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#14]
Kontakt page:
https://github.com/shandya/gimmickmedia/issues/9
Warnanya "map" udah oke Shandy... tapi layout kontaktnya kayaknya lom benar itu. 

Custom Post Type
https://github.com/shandya/gimmickmedia/issues/5
bisa bikin template single post, redirect ke home aja. jadi nggak ada error not found

Header
https://github.com/shandya/gimmickmedia/issues/4
kayaknya saya yg kurang jelas. mksd sy disini cuma header di halaman utama aja yg fullscreen.

Line (Page Inhalte)
https://github.com/shandya/gimmickmedia/issues/10
http://gimmick.ayo-gawe.com/inhalte/
buat mobile hilangin aja linenya. Maaf lupa kasih tahu, kupikir udah jelas krn implementasinya bs di bilang ga mungkin sama sekali, jadi aneh layoutnya juga nanti. yg desktop aja yg di perhatiin.

Reference
https://github.com/shandya/gimmickmedia/issues/12
Shandy disini ada Error coba check disini, abis click buttonnya
http://gimmick.ayo-gawe.com/referenzen/
stylenya messed up...
trus coba click yg item no 12 itu
kebetulan tak display image popup juga... layoutnya tolong di sesuai, close button ama paddingnya.

Main Menu
https://github.com/shandya/gimmickmedia/issues/13
Text decorationnya kykna masih ada linenya itu. dia cuma muncul pas focus aja.
tambahin ini aja k scss nya
.navbar .nav-list-item a:focus {
text-decoration: none;
}

**Comment by shandya** [comment]
Untuk update push paling baru:

![gimmick-kontakt](https://cloud.githubusercontent.com/assets/4597656/12989433/31904742-d138-11e5-9ff7-02241d700400.jpg)
#9 Pada page Kontakt ada kotak border hitam, ini fungsinya buat apa ya? Masih belum tau.

#5 udah dikasih redirect home

#4 udah dimodif lagi cuma header home (slideshow) yang fullscreen

#10 udah dikasih line (untuk tablet ke atas aja)

#12 masih dalam proses

#13 udah dihilangin text decoration pada focusnya.

**Comment by erwin-gimmick** [comment]
Itu contact form, Shandy.

#10 udah dikasih line (untuk tablet ke atas aja), Yup, udah tak lihat, tq, btw buat Mobile, ilangin aja imagenya pas mobile..

Oia satu lagi mengenai parallax itu, di page Inhalte ama Tools, sepertinya parallaxnya posisinya nggak benar, itu pengaruh ukuran fotonya apa gmn yah? biar tahu n nanti kt pastiin ukuran fotonya aja. Itu backgroundnya tumpang tindih, tidak seperti parallax yang lainnya.

**Comment by erwin-gimmick** [comment]
Shandy beberapa bagian masih nggak seperti layout, kyk yg inhalte punya... itu text-align nya, yg km perbaiki itu "linenya". Text alignya kiri n kanan agak beda tapi orientasinya ke tengah gt....
