### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#15]
![2016-02-15-123724_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/13047664/fa57b23c-d3e0-11e5-878f-e1fe7647e760.png)

Shandy ada solusi buat ini ga? itu parallaxny kayak gitu.

**Comment by shandya** [comment]
Kemarin saya sudah push fix untuk parallaxnya. Coba ditarik lagi mungkin belum keupdate.

**Comment by erwin-gimmick** [comment]
udah di tarik shandy, cuma kemren ada text di template yg di ubah... n aku ga bisa merging krn nggak bs push dari localnya sy... bs kasih write permission, sy bikin branch baru sih.
