### ISSUE TITLE
Sidemenu

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#2]
Sidemenu, warnanya udah benar, cuma itu kl hover harusnya warnanya sesuai masing masing page itu, jadi warnanya ikut ke pagenya gt. kl bngung tanya lagi aja.

**Comment by erwin-gimmick** [comment]
![2016-02-09-111750_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/12913416/dda51f38-cf1e-11e5-8bc8-df05941fc1ea.png)

Ini yang aku maksud Shandy

**Comment by shandya** [comment]
Ini sudah saya update lagi di push terakhir.
