### ISSUE TITLE
Reference items

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#20]
"aneh abis update skr weitere Inhalte kyk sebelumnya lagi Shandy, Itemnya tumpang tindih lagi."
ini belum fixed Shandy.

**Comment by shandya** [comment]
Ini saya agak bingung juga, soalnya di local saya ga ada  masalah apa2. Bisa discreen shotin ga? Atau copasin console lognya.

**Comment by erwin-gimmick** [comment]
![2016-02-17-144659_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/13111356/a5141ada-d585-11e5-908c-7661a398d950.png)
![2016-02-17-144709_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/13111355/a513050a-d585-11e5-9a2f-9b93d8cb3ef4.png)

coba check aja di live gimmick.ayo-gawe.com

**Comment by erwin-gimmick** [comment]
![2016-02-17-144901_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/13111367/b7375d94-d585-11e5-9536-5a70c7d3f474.png)

icon nya kyk gt

**Comment by shandya** [comment]
Sudah diperbaiki pd push terakhir ya.

**Comment by shandya** [comment]
Update icon closenya sudah dipush lagi ya.

**Comment by erwin-gimmick** [comment]
Moga nggak error ini, tak benerin juga tadi...
