### ISSUE TITLE
Email Setting

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#21]
Shandy, km test ga contact formnya? tak test tadi pake smtp, pake server sendiri ga bs, pake gmail account juga ga bisa. ga yakin salahnya di email accountnya itu. mungkin settingny sy ga bnr.

**Comment by shandya** [comment]
Enggg... Belum, karena belum sempat dinaikin ke server sendiri. Tunggu ya saya cobain dulu.

**Comment by shandya** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/4597656/13130825/a43b6070-d619-11e5-9d7e-dfddbd1dd302.jpg)

Ga ada setting aneh2 lagi sih, paling template emailnya yang dimodifikasi sesuai field yang ada.
Kalau ngeliat di sini sih kemungkinan hosting issues atau emailnya kena mark spam. http://contactform7.com/setting-up-mail/#Contact_Form_7_Email_Issues

Pakai SMTP itu nambah plugin lagi ya?

**Comment by erwin-gimmick** [comment]
Seharusnya nggak sih, di setting reading ada configurationnya.
Server, Portnya, email n password. server g drumah sih, bisa jadi error krn certificated nya self signed.
cuma aneh aja kl pake gmail juga error. dia error ga ngirim email. trus ga ada request k mail server sih. tar coba lihat aja, kl server bos g ga pake smtp authentication.
