### ISSUE TITLE
Modal Scroll on Tablet

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#22]
di Tablet pas scroll, cuma backgroundnya yg ke scroll, lihatnya pas di Ipad, di browser tablet lain belum tahu sy.

Ah kayaknya issuenya di sini krn foto referencenya panjang, n modal nya fixed yah ato absolute positionya.. jadinya ga mau scroll...
br check ada overflownya tapi, ga mungkin juga krn fix trus ga bs scroll aneh. tolong di check yah.

selain itu, modalnya juga. icon closenya di luar modalnya malah itu.
margin rightnya -3rem

**Comment by shandya** [comment]
Modalnya sudah diperbaiki pd push terakhir.

Untuk icon close saya mengikuti screenshot modal yang dishare kemarin. Di sana icon closenya di luar dan berwarna merah. Apa balikin lagi ke dalam?

**Comment by erwin-gimmick** [comment]
nih designer yg ga bnr ini. di jpg g di dalam malah. di masukin aja Shandy
