### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#4]
Headernya nggak pas ke windowsnya... lebih tinggi heightnya.

**Comment by shandya** [comment]
Headernya itu yang gambar gajah kan ya?

Ini ngikutin PSDnya sih, atau dibuat heightnya ngikutin tinggi browser aja?

**Comment by erwin-gimmick** [comment]
iya ikutin tinggi browsernya... full screen.. kyk di descripti project udah tak tulis begitu kemarin

**Comment by erwin-gimmick** [comment]
Shandy kyknya km salah nangkap "Cuma halaman utama aja yg fullscreen". Halaman utama headernya khan slide itu.
yg sy maksud iya itu ikutin tinggi browsernya Shandy
