### ISSUE TITLE
Page Agentur

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#6]
Itu Textnya bener center yah posisinya? di layout yg aku punya left itu, plus padding di foto coworkernya ga ada.

coba check disini Shandy http://gimmick.ayo-gawe.com/agentur/
Mungkin layoutku yg lama, nanti aku cross check dl dah.. soalnya ga bisa buka file PSD nya.

**Comment by shandya** [comment]
![gimmick-agentur](https://cloud.githubusercontent.com/assets/4597656/12936793/78aab82a-cfd4-11e5-95f3-28256693e1fb.jpg)
Kalau di JPGnya sih begini.

Oh ya untuk section Unsere Marken perlu dibuat CMSnya tidak?

Padding bottom coworkernya sudah ditambah di push terakhir.

**Comment by erwin-gimmick** [comment]
Marken nggak usah cmsnya.. sengaja sy suruh kurangin.

itu yg gambar coworkernya paddingnya antara gambar ke block berikutnya di live website nggak ada.

**Comment by erwin-gimmick** [comment]
![old](https://cloud.githubusercontent.com/assets/8277695/12947299/a4a7dc16-cffa-11e5-9576-d5dc831656a4.jpg)

soal textnya kykny udah benar soalnya saya lihatnya dari yg ini sih kemarin, cuma padding aja yg masih beda ma layout
