### ISSUE TITLE
Youtube Video

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#7]
![2016-02-09-113303_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8277695/12913794/200848ee-cf21-11e5-9a32-bc991c3f690e.png)

Ini harusnya Youtube Videonya Pop Up

**Comment by shandya** [comment]
Sudah jalan fungsi pop up videonya ya. Tapi cek dulu soalnya ga dapet desain pop up windownya, siapa tau perlu perubahan.

**Comment by erwin-gimmick** [comment]
udah oke sih gitu aja, nanti kl dia mau ubah, nanti tak urusin aja.
