### ISSUE TITLE
Icon Footer

### ISSUE THREAD

**Issue by erwin-gimmick** [shandya/gimmickmedia#9]
![2016-02-09-113839_1875x1016_scrot](https://cloud.githubusercontent.com/assets/8277695/12913938/e91c041e-cf21-11e5-8042-ae1068a976ad.png)

Kemarin Intan nanya lwt Trello tak lupa update k sini juga, btw, itu iconnya ganti icon yg seperti ini aja bisa nggak ato musti image?

**Comment by shandya** [comment]
Saya bingung, icon footer itu maksudnya yang mana ya?

**Comment by erwin-gimmick** [comment]
Icon Mapnya, Shandy...

**Comment by shandya** [comment]
Sudah saya update lagi icon mapnya pake yg itu.. Coba cek kira2 aneh tidak?

Untuk warna petanya gimana perlu diganti kah?

Kemarin sih saya ngambil temanya dari https://snazzymaps.com/ siapa tau ada yg lebih bagus.

**Comment by erwin-gimmick** [comment]
Warnanya udah oke Shandy... tapi layout kontaktnya kayaknya lom benar itu.
